/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author delim
 */
public class Retragere extends javax.swing.JFrame {
        Connection con;
      int id;
    public Retragere() {
        initComponents();
    }

    Retragere(int id_c) throws SQLException {
            initComponents();
              id=id_c;
     
          //realizeaza conexiunea la BD
        String database="jdbc:mysql://localhost:3306/Banca";
        String username="root";
        String pass="";
              con=DriverManager.getConnection(database,username,pass);
     IncarcareInformatii();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelEuro = new javax.swing.JLabel();
        LabelLei = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextEuro = new javax.swing.JTextField();
        TextLei = new javax.swing.JTextField();
        BtnRetragere = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sold Euro");

        jLabel2.setText("Sold Lei");

        LabelEuro.setText("jLabel3");

        LabelLei.setText("jLabel4");

        jLabel3.setText("Retragere Lei:");

        jLabel4.setText("Retragere Euro:");

        TextEuro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextEuroKeyReleased(evt);
            }
        });

        TextLei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextLeiKeyReleased(evt);
            }
        });

        BtnRetragere.setText("Retrage fonduri");
        BtnRetragere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRetragereMouseEntered(evt);
            }
        });
        BtnRetragere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetragereActionPerformed(evt);
            }
        });

        jLabel5.setText("Retragere fonduri");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelLei)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextEuro, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(TextLei))
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(BtnRetragere))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelEuro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelLei))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextLei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(BtnRetragere)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEuroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextEuroKeyReleased
    if(DoarNumar(TextEuro.getText())==0)
             JOptionPane.showMessageDialog(null, "Ati introdus un caracter nepermis", "Eroare: " + "Caracter nepermis", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_TextEuroKeyReleased

    private void TextLeiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextLeiKeyReleased
        if(DoarNumar(TextLei.getText())==0)
             JOptionPane.showMessageDialog(null, "Ati introdus un caracter nepermis", "Eroare: " + "Caracter nepermis", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_TextLeiKeyReleased

    //se verifica daca informatiile introduse sunt corespunzatoare pentru a retrage bani
    private void BtnRetragereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRetragereMouseEntered
      
       String euro= TextEuro.getText();
       String lei=TextLei.getText();
       
       if(!euro.isBlank())
           if(DoarNumar(euro)==1)
           {
               if(!lei.isBlank())
                 if(DoarNumar(lei)==1)
             BtnRetragere.setEnabled(true);
                else
             BtnRetragere.setEnabled(false);
          else
                    BtnRetragere.setEnabled(true);
           }
              else
                    BtnRetragere.setEnabled(false);
            
       
         if(!lei.isBlank())
             if(DoarNumar(lei)==1)
             { 
                 if(!euro.isBlank())
                     if(DoarNumar(euro)==1)
                         BtnRetragere.setEnabled(true);
                    else
                        BtnRetragere.setEnabled(false);
       else
                    BtnRetragere.setEnabled(true);
             
             }
          else
                    BtnRetragere.setEnabled(false);
          if(euro.isBlank()&&lei.isBlank())
           BtnRetragere.setEnabled(false);
   
     
       
    }//GEN-LAST:event_BtnRetragereMouseEntered

    private void BtnRetragereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetragereActionPerformed
        int row=0;
          if(!TextEuro.getText().isBlank())
          {
              try {
                  Float euro=Float.parseFloat(TextEuro.getText());
                  Float sold=Float.parseFloat(LabelEuro.getText());
                  Float nousold=sold-euro;
                  String query="Update Client set Sold_Cont_EURO="+nousold+" where ID_C="+id;
                  Statement s=con.createStatement();
                   row=s.executeUpdate(query);
                  
              } catch (SQLException ex) {
                  Logger.getLogger(Retragere.class.getName()).log(Level.SEVERE, null, ex);
              }

               
          }
           if(!TextLei.getText().isBlank())
           {
              try {
                  Float lei=Float.parseFloat(TextLei.getText());
                  Float sold=Float.parseFloat(LabelLei.getText());
                  Float nousold=sold-lei;
                  String query="Update Client set Sold_Cont_LEI="+nousold+" where ID_C="+id;
                  Statement s=con.createStatement();
                   row=s.executeUpdate(query);
                  
              } catch (SQLException ex) {
                  Logger.getLogger(Retragere.class.getName()).log(Level.SEVERE, null, ex);
              }

           }
           if(row>0)
                  {
                      JOptionPane.showMessageDialog(null, "Retragerea a fost efectuata cu succes", "Succes: " + "Retragere numerar", JOptionPane.INFORMATION_MESSAGE);
                     
                  }
                  else
                      JOptionPane.showMessageDialog(null, "A aparut o eroare", "Eroare: " + "Ceva nu a functionat bine", JOptionPane.ERROR_MESSAGE);
           IncarcareInformatii();
    }//GEN-LAST:event_BtnRetragereActionPerformed

   
    int DoarNumar(String text)
   {
       String regex = "^.{0}$|^[0-9]+"; //regex pentru a fi doar numere sau un sir null
        if(text.matches(regex))
            return 1;  
        else 
            return 0;
         
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retragere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retragere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retragere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retragere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retragere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRetragere;
    private javax.swing.JLabel LabelEuro;
    private javax.swing.JLabel LabelLei;
    private javax.swing.JTextField TextEuro;
    private javax.swing.JTextField TextLei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void IncarcareInformatii() {
     
        TextEuro.setText("");
        TextLei.setText("");
        try{
            String query="Select * from Client where ID_C="+id;
      Statement statement =con.createStatement();
      ResultSet rs=statement.executeQuery(query);
      while(rs.next())
      { //preia informatia despre conturi
        LabelEuro.setText(rs.getString("Sold_Cont_EURO")); 
         LabelLei.setText(rs.getString("Sold_Cont_LEI"));
      }
          } catch (SQLException ex) {
              Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
          }
    }
}
